version: "3.7"
volumes:
  mysql-data: {}
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=petclinic
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
  app:
    build: .
    container_name: petclinic
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "-X", "GET", "http://localhost:8080/petclinic" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

