version: "3.9"
volumes:
  mysql-data: {}
services:
  mysql:
    extends:
      file: spring-petclinic/docker-compose.yml
      service: mysql
  app:
    extends:
      file: spring-petclinic/docker-compose.yml
      service: app
  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/volume:/usr/share/nginx/html/
    ports:
      - "80:80"
    restart: always